# Generated by Django 3.2.3 on 2021-05-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='Red', max_length=20),
        ),
    ]
