# Generated by Django 3.2.3 on 2021-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.TextField(default='cyan'),
        ),
    ]
