# Generated by Django 3.2.3 on 2021-06-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author'),
        ('articles', '0004_tag_color'),
    ]

    operations = [
    ]
