# Generated by Django 3.2.3 on 2021-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_0004_alter_article_author_0004_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sheet_ds',
            field=models.JSONField(),
        ),
    ]
